# Generated by Django 3.1.2 on 2021-12-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fullname',
            new_name='name',
        ),
    ]
