# Generated by Django 3.1.2 on 2021-12-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_auto_20211217_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
