# Generated by Django 3.1.2 on 2021-12-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_auto_20211217_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('is_premium', 'is_premium'), ('is_not_premium', 'is_not_premium')], default='', help_text='The status of this subscription.', max_length=100),
        ),
    ]
