# Generated by Django 3.2.8 on 2021-12-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_auto_20211218_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
